version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: chinese-llm-kb-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: chinese-llm-kb-api
    depends_on:
      - db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./data:/app/data
    restart: always

volumes:
  postgres_data:
